name: flutter_tabs_starter
description: "A new Flutter projec, with tab navigation and no state management."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_slidable: ^3.1.0
  go_router: ^12.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  modal_bottom_sheet: ^3.0.0
  path_provider: ^2.1.2
  provider: ^6.1.2
  sqflite: ^2.3.2

  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
